Test

diff --git a/.github/workflows/14status_check.yaml b/.github/workflows/14status_check.yaml
--- a/.github/workflows/14status_check.yaml
+++ b/.github/workflows/14status_check.yaml
@@ -6,7 +6,12 @@ jobs:
         runs-on: ubuntu-latest
         steps:
         - name: Step 1
-          run: sleep 20 
+          run: sleep 20
+        - name: Step 2 
+          run: exit 1 
+        - name: Runs on Failure 
+          if: steps.step-2.conclusion == 'failure'
+          run: echo 'Step 2 hads failed' 
         - name: Fail 
           run: exit 1
         - name: Runs on Failure
